console:
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        template:
          metadata:
            name: "[[.ApplicationName]]-[[.Console.Name]]"
          spec:
            containers:
              - name: "[[.ApplicationName]]-[[.Console.Name]]"
                env:
                  - name: MAVEN_MIRROR_URL
                    value: ""
                  - name: MAVEN_REPO_ID
                    value: ""
                  - name: MAVEN_REPO_URL
                    value: ""
                  - name: MAVEN_REPO_USERNAME
                    value: ""
                  - name: MAVEN_REPO_PASSWORD
                    value: ""
                  - name: JGROUPS_PING_PROTOCOL
                    value: ""
                  - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                    value: ""
                  - name: OPENSHIFT_DNS_PING_SERVICE_PORT
                    value: ""
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
  persistentVolumeClaims:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-claim"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  services:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-ping"
        annotations:
          delete: "true"
