#! package-manifest: deploy/catalog_resources/redhat/7.8/businessautomation-operator.7.8.1.clusterserviceversion.yaml
channels:
- currentCSV: businessautomation-operator.7.8.1
  name: stable
packageName: businessautomation-operator
