console:
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        template:
          metadata:
            name: "[[.ApplicationName]]-[[.Console.Name]]"
          spec:
            containers:
              - name: "[[.ApplicationName]]-[[.Console.Name]]"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
  persistentVolumeClaims:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-claim"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  services:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-ping"
        annotations:
          delete: "true"
## KIE smartrouter BEGIN
smartRouter:
  omit: true
## KIE smartrouter END
