apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: openshift-startup-strategy
spec:
  environment: rhpam-trial
  objects:
    console:
      env:
        - name: KIE_SERVER_CONTROLLER_OPENSHIFT_GLOBAL_DISCOVERY_ENABLED
          value: "true"
        - name: KIE_SERVER_CONTROLLER_OPENSHIFT_PREFER_KIESERVER_SERVICE
          value: "true"
        - name: KIE_SERVER_CONTROLLER_TEMPLATE_CACHE_TTL
          value: "60000"
        - name: KIE_WORKBENCH_CONTROLLER_OPENSHIFT_ENABLED
          value: "true"
    servers:
      - env:
          - name: KIE_SERVER_STARTUP_STRATEGY
            value: "OpenShiftStartupStrategy"
      - id: testing
        env:
          - name: KIE_SERVER_STARTUP_STRATEGY
            value: "OpenShiftStartupStrategy"
