apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: keystore-config
  annotations:
    consoleName: snippet-keystore-config
    consoleTitle: Configure Keystores
    consoleDesc: Use this snippet to configure keystores
    consoleSnippet: true
spec:
  objects:
    console:
      keystoreSecret: console-keystore
    servers:
      - name: server-a
        deployments: 2
        keystoreSecret: server-a-keystore
      - name: server-b
        keystoreSecret: server-b-keystore
