apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: server-mysqldb
  annotations:
    consoleName: snippet-server-mysqldb
    consoleTitle: Configure MySQL DB for Servers
    consoleDesc: Use this snippet to configure mysql db for servers
    consoleSnippet: true
spec:
  objects:
    servers:
      - deployments: 2
        database:
          type: mysql
          size: 30Gi
      - deployments: 1
        database:
          type: mysql
          size: 30Gi
          storageClassName: gold
