#! package-manifest: deploy/catalog_resources/community/1.2.0/kiecloud-operator.1.2.0.clusterserviceversion.yaml
packageName: kiecloud-operator
channels:
  - name: stable
    currentCSV: kiecloud-operator.1.2.0
