## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            metadata:
              name: "[[.KieName]]"
            spec:
              containers:
                - name: "[[.KieName]]"
                  volumeMounts:
                    - name: "[[.KieName]]-h2-pvol"
                      mountPath: "/opt/eap/standalone/data"
## [[ if ne .Database.Size "" ]]
              volumes:
                ## H2 volume settings BEGIN
                - name: "[[.KieName]]-h2-pvol"
                  persistentVolumeClaim:
                    claimName: "[[.KieName]]-h2-claim"
    ## KIE server deployment config END
    persistentVolumeClaims:
      ## H2 persistent volume claim BEGIN
      - metadata:
          name: "[[.KieName]]-h2-claim"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "[[.Database.Size]]"
      ## H2 persistent volume claim END
## [[ else ]]
              volumes:
                ## H2 volume settings BEGIN
                - name: "[[.KieName]]-h2-pvol"
                  emptyDir: {}
## [[ end ]]
#[[end]]
## RANGE ends
## KIE Servers END
