#! package-manifest: deploy/catalog_resources/redhat/1.2.1/businessautomation-operator.1.2.1.clusterserviceversion.yaml
packageName: businessautomation-operator
channels:
  - name: stable
    currentCSV: businessautomation-operator.1.2.1
