apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: common-config
spec:
  environment: rhpam-trial
  commonConfig:
    # By default is the cr.Name
    applicationName: other
    adminPassword: example
