apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: keystore-config
spec:
  environment: rhpam-trial
  objects:
    console:
      gitHooks:
        mountPath: /githooks
        from:
          kind: PersistentVolumeClaim
          name: githooks-pvc
