apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: jvm-config
spec:
  environment: rhpam-trial
  objects:
    console:
      jvm:
        javaOptsAppend: "-Dthing=console"
        javaMaxMemRatio: 80
        javaInitialMemRatio: 40
    servers:
      - jvm:
          javaOptsAppend: "-Dthing=server"
          javaMaxMemRatio: 80
          javaInitialMemRatio: 40
