apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: keystore-config
spec:
  environment: rhpam-trial
  objects:
    console:
      keystoreSecret: console-keystore
    servers:
      - name: server-a
        deployments: 2
        keystoreSecret: server-a-keystore
      - name: server-b
        keystoreSecret: server-b-keystore
