apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: process-migration
spec:
  environment: rhpam-trial
  objects:
    processMigration:
      database:
        type: "postgresql"
        size: 30Gi
        storageClassName: gold
