apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhdm-production-immutable
  annotations:
    consoleName: rhdm-production-immutable
    consoleTitle: DM Production Immutable
    consoleDesc: Deploys a DM Production Immutable environment
spec:
  environment: rhdm-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhdm-kieserver-hellorules=org.openshift.quickstarts:rhdm-kieserver-hellorules:1.6.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhdm-7-openshift-image.git
            reference: master
            contextDir: quickstarts/hello-rules/hellorules
          # uncomment the block below to set custom environment variable for BuildConfig, useful to configure JAVA_OPTS_APPEND or other
          # properties such as MAVEN_OPTS_APPEND
          # env:
          #  - name: "JAVA_OPTS_APPEND"
          #    value: "-Dmy.custom.property=prop-test"

