apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-production-immutable
  annotations:
    consoleName: rhpam-production-immutable
    consoleTitle: PAM Production Immutable
    consoleDesc: Deploys a PAM Production Immutable environment
spec:
  environment: rhpam-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhpam-kieserver-library=org.openshift.quickstarts:rhpam-kieserver-library:1.6.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhpam-7-openshift-image.git
            reference: master
            contextDir: quickstarts/library-process/library
          # uncomment the block below to set custom environment variable for BuildConfig, useful to configure JAVA_OPTS_APPEND or other
          # properties such as MAVEN_OPTS_APPEND
          # env:
          #  - name: "JAVA_OPTS_APPEND"
          #    value: "-Dmy.custom.property=prop-test"
