apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: server-external-db
spec:
  environment: rhpam-trial
  objects:
    servers:
      - name: test-oracle
        database:
          type: external
          externalConfig:
            driver: oracle
            dialect: org.hibernate.dialect.OracleDialect
            username: orauser
            password: orapwd
            jdbcURL: jdbc:oracle:thin:@oracleHostName:1521:orcl
      - name: test-mysql
        database:
          type: external
          externalConfig:
            driver: mysql
            dialect: org.hibernate.dialect.MySQL8Dialect
            host: mysql.example.com
            port: "3306"
            name: rhpam1
            username: otheruser
            password: otherpwd
